name: ionbus

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0.15
    container_name: ionbus_mqtt
    env_file:
      - ../.env
    ports:
      - "${MQTT_PORT}:${MQTT_PORT}"
      - "${MQTT_WS_PORT}:${MQTT_WS_PORT}"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: ionbus_rabbit
    env_file:
      - ../.env
    ports:
      - "${RABBIT_PORT}:${RABBIT_PORT}"
      - "${RABBIT_MANAGEMENT_PORT}:${RABBIT_MANAGEMENT_PORT}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: ionbus_db
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  rabbitmq_data:
  postgres_data:
  mqtt_data:
  mqtt_log: